version: '3'

services:
  # Locust Master - Web UI and coordination (FastHttpUser version)
  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"  # Web UI
    volumes:
      - ./locustfile-fast.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master --master-bind-host=0.0.0.0 --host=http://host.docker.internal:8080
    networks:
      - locust-network

  # Locust Worker - Executes the load tests with C-based HTTP client
  locust-worker:
    image: locustio/locust
    volumes:
      - ./locustfile-fast.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust-master
    depends_on:
      - locust-master
    networks:
      - locust-network

networks:
  locust-network:
    driver: bridge
